import { StyleSheet } from "@react-pdf/renderer";

export const colors = {
  emerald50: "#ecfdf5",
  emerald100: "#d1fae5",
  emerald600: "#059669",
  emerald700: "#047857",
  slate50: "#f8fafc",
  slate100: "#f1f5f9",
  slate200: "#e2e8f0",
  slate400: "#94a3b8",
  slate500: "#64748b",
  slate600: "#475569",
  slate700: "#334155",
  slate900: "#0f172a",
  amber50: "#fffbeb",
  amber700: "#b45309",
  sky50: "#f0f9ff",
  sky700: "#0369a1",
};

export const pdfStyles = StyleSheet.create({
  page: {
    fontFamily: "Helvetica",
    fontSize: 10,
    color: colors.slate700,
    paddingTop: 40,
    paddingBottom: 60,
    paddingHorizontal: 48,
    backgroundColor: "#ffffff",
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 28,
    paddingBottom: 20,
    borderBottomWidth: 2,
    borderBottomColor: colors.emerald600,
  },
  logoSection: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  logo: {
    width: 48,
    height: 48,
    objectFit: "contain",
  },
  brandName: {
    fontSize: 18,
    fontFamily: "Helvetica-Bold",
    color: colors.slate900,
    letterSpacing: -0.3,
  },
  brandTagline: {
    fontSize: 8,
    color: colors.slate500,
    marginTop: 2,
    letterSpacing: 0.5,
    textTransform: "uppercase",
  },
  metaBlock: {
    alignItems: "flex-end",
  },
  metaLabel: {
    fontSize: 7,
    color: colors.slate400,
    textTransform: "uppercase",
    letterSpacing: 0.8,
    marginBottom: 2,
  },
  metaValue: {
    fontSize: 10,
    color: colors.slate700,
    fontFamily: "Helvetica-Bold",
    marginBottom: 6,
  },
  title: {
    fontSize: 22,
    fontFamily: "Helvetica-Bold",
    color: colors.slate900,
    marginBottom: 6,
    letterSpacing: -0.5,
  },
  subtitle: {
    fontSize: 11,
    color: colors.slate500,
    marginBottom: 20,
    lineHeight: 1.5,
  },
  section: {
    marginBottom: 20,
  },
  sectionTitle: {
    fontSize: 11,
    fontFamily: "Helvetica-Bold",
    color: colors.slate900,
    marginBottom: 10,
    paddingBottom: 4,
    borderBottomWidth: 1,
    borderBottomColor: colors.slate200,
    textTransform: "uppercase",
    letterSpacing: 0.6,
  },
  propertyGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    backgroundColor: colors.slate50,
    padding: 14,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: colors.slate200,
  },
  propertyItem: {
    width: "30%",
    minWidth: 120,
  },
  propertyLabel: {
    fontSize: 7,
    color: colors.slate400,
    textTransform: "uppercase",
    letterSpacing: 0.6,
    marginBottom: 3,
  },
  propertyValue: {
    fontSize: 10,
    fontFamily: "Helvetica-Bold",
    color: colors.slate900,
  },
  totalsRow: {
    flexDirection: "row",
    gap: 10,
    marginBottom: 20,
  },
  totalCard: {
    flex: 1,
    padding: 12,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: colors.slate200,
    alignItems: "center",
  },
  totalCardPrimary: {
    backgroundColor: colors.emerald50,
    borderColor: colors.emerald600,
    borderWidth: 1.5,
  },
  totalLabel: {
    fontSize: 7,
    color: colors.slate500,
    textTransform: "uppercase",
    letterSpacing: 0.6,
    marginBottom: 4,
  },
  totalLabelPrimary: {
    color: colors.emerald700,
  },
  totalAmount: {
    fontSize: 16,
    fontFamily: "Helvetica-Bold",
    color: colors.slate700,
  },
  totalAmountPrimary: {
    color: colors.emerald700,
    fontSize: 18,
  },
  table: {
    borderWidth: 1,
    borderColor: colors.slate200,
    borderRadius: 4,
    overflow: "hidden",
  },
  tableHeader: {
    flexDirection: "row",
    backgroundColor: colors.slate100,
    borderBottomWidth: 1,
    borderBottomColor: colors.slate200,
    paddingVertical: 8,
    paddingHorizontal: 10,
  },
  tableHeaderCell: {
    fontSize: 7,
    fontFamily: "Helvetica-Bold",
    color: colors.slate500,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  tableRow: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: colors.slate100,
    paddingVertical: 9,
    paddingHorizontal: 10,
    alignItems: "flex-start",
  },
  tableRowAlt: {
    backgroundColor: colors.slate50,
  },
  tableCell: {
    fontSize: 9,
    color: colors.slate700,
    lineHeight: 1.4,
  },
  tableCellBold: {
    fontFamily: "Helvetica-Bold",
    color: colors.slate900,
  },
  colDescription: { width: "38%" },
  colCategory: { width: "12%" },
  colQty: { width: "8%", textAlign: "center" },
  colUnit: { width: "10%", textAlign: "center" },
  colUnitPrice: { width: "14%", textAlign: "right" },
  colTotal: { width: "18%", textAlign: "right" },
  bulletList: {
    gap: 6,
  },
  bulletItem: {
    flexDirection: "row",
    gap: 8,
    alignItems: "flex-start",
  },
  bullet: {
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: colors.emerald600,
    marginTop: 4,
  },
  bulletText: {
    flex: 1,
    fontSize: 9,
    color: colors.slate600,
    lineHeight: 1.5,
  },
  alertBox: {
    padding: 10,
    borderRadius: 4,
    marginBottom: 8,
    borderWidth: 1,
  },
  alertWarning: {
    backgroundColor: colors.amber50,
    borderColor: "#fde68a",
  },
  alertSuggestion: {
    backgroundColor: colors.emerald50,
    borderColor: colors.emerald100,
  },
  alertInfo: {
    backgroundColor: colors.sky50,
    borderColor: "#bae6fd",
  },
  alertTitle: {
    fontSize: 9,
    fontFamily: "Helvetica-Bold",
    marginBottom: 3,
  },
  alertMessage: {
    fontSize: 8,
    lineHeight: 1.5,
    color: colors.slate600,
  },
  footer: {
    position: "absolute",
    bottom: 24,
    left: 48,
    right: 48,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: colors.slate200,
  },
  footerText: {
    fontSize: 8,
    color: colors.slate400,
  },
  footerBrand: {
    fontSize: 8,
    color: colors.emerald600,
    fontFamily: "Helvetica-Bold",
  },
  validityBadge: {
    backgroundColor: colors.emerald50,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 4,
    marginTop: 8,
    alignSelf: "flex-start",
  },
  validityText: {
    fontSize: 8,
    color: colors.emerald700,
    fontFamily: "Helvetica-Bold",
  },
});